// A small curated word list, not the full EFF diceware list - good enough
// for a demo, and short enough to read/audit at a glance. All lowercase,
// no duplicates, no punctuation, so joining/capitalizing is trivial.
const WORDLIST = [
  'anchor', 'apple', 'arrow', 'autumn', 'badge', 'banjo', 'basil', 'beacon',
  'bench', 'berry', 'bicycle', 'birch', 'bison', 'blanket', 'blossom', 'bolt',
  'bonfire', 'boulder', 'branch', 'breeze', 'bridge', 'bucket', 'bugle',
  'cabin', 'cactus', 'camel', 'camera', 'canyon', 'castle', 'cedar', 'cellar',
  'chalk', 'channel', 'cherry', 'chimney', 'clover', 'coast', 'comet',
  'compass', 'copper', 'coral', 'cotton', 'cradle', 'crater', 'cricket',
  'crimson', 'crystal', 'current', 'daisy', 'dawn', 'delta', 'desert',
  'diamond', 'dolphin', 'dragon', 'drift', 'eagle', 'ember', 'emerald',
  'engine', 'falcon', 'feather', 'fern', 'fiddle', 'field', 'flame',
  'flannel', 'flint', 'forest', 'fossil', 'fountain', 'fox', 'garden',
  'garnet', 'gazelle', 'ginger', 'glacier', 'glider', 'gopher', 'granite',
  'gravel', 'gully', 'hammer', 'harbor', 'harvest', 'hazel', 'heather',
  'hickory', 'hollow', 'honey', 'horizon', 'hunter', 'iguana', 'indigo',
  'island', 'ivory', 'jacket', 'jade', 'jasmine', 'jasper', 'jungle',
  'kayak', 'kernel', 'kettle', 'kite', 'lagoon', 'lantern', 'larch',
  'lavender', 'ledge', 'lemon', 'lentil', 'lichen', 'linen', 'lobster',
  'locust', 'lumber', 'magpie', 'mallow', 'maple', 'marble', 'marsh',
  'meadow', 'melon', 'mesa', 'meteor', 'mimosa', 'mint', 'mirror', 'mist',
  'monsoon', 'moose', 'moraine', 'moss', 'nectar', 'needle', 'nettle',
  'noble', 'nomad', 'nutmeg', 'oak', 'oasis', 'obsidian', 'ocean', 'olive',
  'onyx', 'opal', 'orbit', 'orchard', 'orchid', 'osprey', 'otter', 'paddle',
  'panther', 'papaya', 'parchment', 'pebble', 'pecan', 'pelican', 'pepper',
  'petal', 'pigeon', 'pillow', 'pine', 'pioneer', 'plateau', 'plum',
  'pocket', 'poplar', 'poppy', 'prairie', 'pretzel', 'quail', 'quarry',
  'quartz', 'quiver', 'rabbit', 'raccoon', 'rainbow', 'raven', 'reef',
  'ridge', 'river', 'robin', 'rocket', 'rooster', 'rustic', 'saddle',
  'saffron', 'sage', 'salmon', 'sandbar', 'sapphire', 'satin', 'savanna',
  'sequoia', 'shadow', 'shale', 'shelter', 'shimmer', 'shovel', 'shrimp',
  'sierra', 'silo', 'sketch', 'skyline', 'slate', 'sleigh', 'sonar',
  'sorrel', 'sparrow', 'spice', 'spring', 'spruce', 'squash', 'stable',
  'stallion', 'starling', 'summit', 'sunset', 'swallow', 'swan', 'tangerine',
  'tavern', 'temple', 'terrace', 'thicket', 'thistle', 'thunder', 'timber',
  'toast', 'tortoise', 'trellis', 'trumpet', 'tulip', 'tundra', 'turtle',
  'twig', 'umbrella', 'valley', 'velvet', 'venture', 'violet', 'voyage',
  'walnut', 'walrus', 'warbler', 'wattle', 'whistle', 'willow', 'wisteria',
  'wolf', 'wren', 'yarrow', 'zephyr',
];
